### ISSUE TITLE
TODO: Do we want to use the Meetup API

### ISSUE THREAD

**Issue by mfmunic** [jhuynh85/Project1#29]
Question for Saturday's class.  We need another API key.  Jeff suggested using Meetup's API.  I started looking into today.  There is a lot of documentation, and looks fairly easy to use.  I would be willing to take this on, but I will need a little help getting started.

**Comment by jhuynh85** [comment]
Yeah, we can use the Meetup API. 

One issue that I can think of though is that we will have to display it differently than the other categories because meetups have an event name in addition to address/phone/etc. But we can probably solve that by having a separate table for meetups that is hidden by default and only appear when the user selects the 'Meetup' category.

@mfmunic, you're welcome to take ownership of this if you like. I'll close this issue and create a new one with the functions we will need.
