### ISSUE TITLE
Core functionality: Validate user address and handle failures to lookup coordinate

### ISSUE THREAD

**Issue by jhuynh85** [jhuynh85/Project1#80]
Ensure that site fails gracefully if user-inputted address does not return a coordinate.

For example "11514 Elbert Ct." is a valid address but will cause an error.

**Comment by andyhe0x21** [comment]
fixed in #91 

- Blank Map -
it is because map drawing code was guarded by a if statement which checks if the length of result location array is larger than 0).

- Home Marker Not Centered -
Also, I found random issue with map centering. If we search for bigger cities like LA, SF and Portland, map is not centered, while searching for small cities like Riverside, Irvine, Camas, WA, there is no such issue. I guess this is because bigger cities are frequently searched so there may be some kind of "Cache" to make query much faster, which causes difference in async order of code execution.

I added extra delay to function displayMap so the above issue was FIXED.
